language: cpp
sudo: required
dist: trusty
compiler:
- gcc
- clang
os:
- linux
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq freeglut3 mesa-utils
script: make
branches:
  only:
  - master
